#!/usr/bin/env python3
"""Put the published version on the README that ships beside it.

The publish job rewrites Chart.yaml to the build's CalVer, but the README is
generated by helm-docs and keeps the version committed in git. `helm show
readme` on the published artifact then advertises a version that was never
released, next to install instructions for one that was.

Regenerating with helm-docs would work and costs a toolchain in the publish
job for two numbers. This rewrites the two badges instead, and fails when it
cannot find them: a silent no-op here restores exactly the bug it fixes.

    stamp_chart_readme.py README VERSION APPVERSION
    stamp_chart_readme.py --self-test
"""
import pathlib
import re
import sys
from pathlib import Path


def badge(label):
    """The helm-docs badge for one field, whatever version it currently names."""
    # Not [^-]+: shields.io reads a single hyphen as a field separator, so a
    # version containing one is written --, and stopping at the first hyphen
    # would miss the badge for 0.3.0-rc.1 and fail the publish with a message
    # about helm-docs changing its format.
    return (
        rf"!\[{label}: [^\]]+\]"
        rf"\(https://img\.shields\.io/badge/{label}-.+?-informational\?style=flat-square\)"
    )


def stamp(readme_text, version, app_version):
    for label, value in (("Version", version), ("AppVersion", app_version)):
        # Escaped the way shields.io reads it, so the rendered badge shows
        # the version rather than splitting on its hyphen.
        replacement = (
            f"![{label}: {value}]"
            f"(https://img.shields.io/badge/{label}-{value.replace('-', '--')}-informational?style=flat-square)"
        )
        readme_text, count = re.subn(
            badge(label), replacement.replace("\\", "\\\\"), readme_text
        )
        if count != 1:
            sys.exit(
                f"expected exactly one {label} badge, found {count}. helm-docs "
                "changed the badge format, so this is no longer rewriting what "
                "it thinks it is."
            )
    return readme_text


def self_test():
    original = (
        "# obico\n\n"
        "![Version: 0.3.0](https://img.shields.io/badge/Version-0.3.0-informational?style=flat-square) "
        "![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) "
        "![AppVersion: 2026.7.11](https://img.shields.io/badge/AppVersion-2026.7.11-informational?style=flat-square)\n"
    )
    stamped = stamp(original, "2026.7.26", "2026.7.26")
    assert "Version-2026.7.26-informational" in stamped, stamped
    assert "![Version: 2026.7.26]" in stamped, stamped
    assert "0.3.0" not in stamped, stamped
    # The Type badge sits between the two and must survive untouched, since
    # a regex loose enough to eat it would also eat any badge added later.
    assert "Type-application-informational" in stamped, stamped
    # AppVersion contains the word Version. Rewriting Version first must not
    # consume it, or the second pass finds nothing and the step fails on a
    # file it had already handled correctly.
    assert stamped.count("informational") == 3, stamped

    # A prerelease version, which carries a hyphen. helm-docs writes it as --
    # in the shield, so a pattern stopping at the first hyphen finds nothing
    # and the publish fails claiming the format changed.
    prerelease = stamp(original, "0.3.0-rc.1", "0.3.0-rc.1")
    assert "Version-0.3.0--rc.1-informational" in prerelease, prerelease
    assert "![Version: 0.3.0-rc.1]" in prerelease, prerelease
    # And stamping the result again finds the badge it just wrote.
    assert "Version-2026.7.27-informational" in stamp(prerelease, "2026.7.27", "2026.7.27")

    # A README without the badges has to stop the publish, not pass quietly.
    try:
        stamp("# obico\n\nno badges here\n", "1.0.0", "1.0.0")
    except SystemExit:
        pass
    else:
        raise AssertionError("a README with no badges was accepted")

    # main() itself, because a file that never writes is exactly the silent
    # no-op this exists to prevent, and every case above would still pass.
    import os
    import tempfile

    previous = os.getcwd()
    try:
        with tempfile.TemporaryDirectory() as tmp:
            os.chdir(tmp)
            readme = pathlib.Path("README.md")
            readme.write_text(original)
            main(["README.md", "2026.7.26", "2026.7.26"])
            assert "Version-2026.7.26-informational" in readme.read_text(), readme.read_text()
            assert "0.3.0" not in readme.read_text()
            readme.write_text("# obico\n\nno badges here\n")
            try:
                main(["README.md", "1.0.0", "1.0.0"])
            except SystemExit:
                pass
            else:
                raise AssertionError("a README with no badges was published")
    finally:
        os.chdir(previous)

    print("self-test ok")


def main(argv):
    if len(argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} README VERSION APPVERSION | --self-test")
    readme, version, app_version = Path(argv[0]), argv[1], argv[2]
    readme.write_text(stamp(readme.read_text(), version, app_version))
    print(f"{readme} now advertises {version}")


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        self_test()
    else:
        main(sys.argv[1:])
