version: '2.4'

services:
  ml_api:
    build:
      context: ml_api
      dockerfile: Dockerfile.rknn
    devices:
      - '/dev/dri/'
    security_opt:
      # The below are needed because the runtime reads /sys/firmware/devicetree/base/compatible
      - systempaths=unconfined
      - apparmor=unconfined