# Generated by Django 2.1.5 on 2019-01-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_printercommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='alert_outstanding',
            field=models.BooleanField(default=False),
        ),
    ]
