# Generated by Django 2.1.7 on 2019-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190219_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprinter',
            name='bed_off_on_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printer',
            name='bed_off_on_pause',
            field=models.BooleanField(default=False),
        ),
    ]
