# Generated by Django 2.1.7 on 2019-02-28 13:59

from django.db import migrations, models
import django.db.models.deletion


def create_printer_prediction_for_existing_printers(apps, schema_editor):
    Printer = apps.get_model("app", "Printer")
    PrinterPrediction = apps.get_model("app", "PrinterPrediction")
    db_alias = schema_editor.connection.alias

    for printer in Printer.objects.all():
        PrinterPrediction.objects.create(printer=printer)

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_phone_num_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterPrediction',
            fields=[
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Printer')),
                ('current_frame_num', models.IntegerField(default=0)),
                ('lifetime_frame_num', models.IntegerField(default=0)),
                ('current_p', models.FloatField(default=0.0)),
                ('ewm_mean', models.FloatField(default=0.0)),
                ('rolling_mean_long', models.FloatField(default=0.0)),
                ('rolling_mean_short', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just notify me via email and text.'), ('PAUSE', 'Pause the print and notify me via email and text.'), ('CANCEL', 'Cancel the print and notifiy me (not available during beta testing).')], default='PAUSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='printer',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just notify me via email and text.'), ('PAUSE', 'Pause the print and notify me via email and text.'), ('CANCEL', 'Cancel the print and notifiy me (not available during beta testing).')], default='PAUSE', max_length=10),
        ),
        migrations.RunPython(create_printer_prediction_for_existing_printers, reverse_func),
    ]
