# Generated by Django 2.1.7 on 2019-03-03 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_detective_sensitivity_to_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='print_status_updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='print_status_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
