# Generated by Django 2.1.7 on 2019-03-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_print_prediction_json_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='lift_z_on_pause',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='historicalprinter',
            name='retract_on_pause',
            field=models.FloatField(default=6.5),
        ),
        migrations.AddField(
            model_name='printer',
            name='lift_z_on_pause',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='printer',
            name='retract_on_pause',
            field=models.FloatField(default=6.5),
        ),
    ]
