# Generated by Django 2.1.7 on 2019-05-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_print_fields_from_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='alert_off',
            field=models.BooleanField(default=False),
        ),
    ]
