# Generated by Django 2.1.7 on 2019-05-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_print_alert_muted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprint',
            name='prediction_json_url',
            field=models.CharField(db_index=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='prediction_json_url',
            field=models.CharField(db_index=True, max_length=2000, null=True),
        ),
    ]
