# Generated by Django 2.1.7 on 2019-07-31 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_index_json_url_to_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprint',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprint',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='current_print',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalPrint',
        ),
        migrations.DeleteModel(
            name='HistoricalPrinter',
        ),
    ]
