# Generated by Django 2.1.7 on 2019-08-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_pushbullet_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprint',
            name='alert_invalidated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprint',
            name='paused_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='alert_invalidated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='paused_at',
            field=models.DateTimeField(null=True),
        ),
    ]
