# Generated by Django 2.1.7 on 2019-08-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_add_addl_alter_dates_to_prints'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprint',
            name='user_feedback',
            field=models.CharField(choices=[('FAILED', 'Yes the print did fail.'), ('SUCCEEDED', 'Nothing was wrong. It was a false alarm.'), ('PARTIALY_FAILED', 'There were some problems. But the print managed to finish anyway.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='user_feedback',
            field=models.CharField(choices=[('FAILED', 'Yes the print did fail.'), ('SUCCEEDED', 'Nothing was wrong. It was a false alarm.'), ('PARTIALY_FAILED', 'There were some problems. But the print managed to finish anyway.')], max_length=20, null=True),
        ),
    ]
