# Generated by Django 2.1.7 on 2019-08-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprint',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalprint',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Printer'),
        ),
        migrations.AlterField(
            model_name='print',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
