# Generated by Django 2.1.7 on 2019-08-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_make_printer_id_nullable_in_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Print'),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='reason',
            field=models.CharField(choices=[('ALERT_OVERWRITE', 'ALERT_OVERWRITE'), ('TIMELAPSE_UPLOAD', 'TIMELAPSE_UPLOAD')], max_length=20),
        ),
    ]
