# Generated by Django 2.1.7 on 2019-11-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190821_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consented_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='reason',
            field=models.CharField(choices=[('ALERT_OVERWRITE', 'ALERT_OVERWRITE'), ('TIMELAPSE_UPLOAD', 'TIMELAPSE_UPLOAD'), ('BUG_REPORT', 'BUG_REPORT')], max_length=20),
        ),
    ]
