# Generated by Django 2.1.7 on 2019-10-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190821_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Print')),
            ],
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='reason',
            field=models.CharField(choices=[('ALERT_OVERWRITE', 'ALERT_OVERWRITE'), ('TIMELAPSE_UPLOAD', 'TIMELAPSE_UPLOAD'), ('BUG_REPORT', 'BUG_REPORT')], max_length=20),
        ),
    ]
