# Generated by Django 2.1.7 on 2019-11-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_consented_at_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED')], max_length=20, null=True)),
                ('alert_muted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Print')),
            ],
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='historicalprinter',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprinter',
            name='watching',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='watching',
            field=models.BooleanField(default=True),
        ),
    ]
