# Generated by Django 2.1.7 on 2019-11-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_consented_at_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED')], max_length=20, null=True)),
                ('alert_muted', models.BooleanField()),
                ('processed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Print')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalprint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='updated_at',
        ),
    ]
