# Generated by Django 2.1.7 on 2019-11-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191104_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='watching',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='watching',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just notify me via email and text.'), ('PAUSE', 'Pause the print and notify me via email and text.')], default='PAUSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalprinter',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just notify me via email and text.'), ('PAUSE', 'Pause the print and notify me via email and text.')], default='PAUSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='printer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='current_print',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_used', to='app.Print'),
        ),
    ]
