# Generated by Django 2.1.11 on 2019-12-11 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_sharedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_notification_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alert_by_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='print_notification_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='print_notification_by_pushbullet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='print_notification_by_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unsub_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
