# Generated by Django 2.1.11 on 2019-12-13 05:10

from django.db import migrations, models
import uuid

def reset_unsub_token(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('app', 'User')
    for user in User.objects.all():
        user.unsub_token = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191212_2101'),
    ]

    operations = [
        migrations.RunPython(reset_unsub_token, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='unsub_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, null=False, blank=False),
        ),
    ]
