# Generated by Django 2.1.11 on 2020-03-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_user_slack_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictimelapse',
            name='frame_p',
        ),
        migrations.AddField(
            model_name='publictimelapse',
            name='p_json_url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
