# Generated by Django 2.2.10 on 2020-05-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200311_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintShotFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
                ('answer', models.CharField(blank=True, choices=[('LOOKS_BAD', 'It contains spaghetti'), ('LOOKS_OK', 'It does NOT contain spaghetti'), ('', "I'll decide later")], max_length=16)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Print')),
            ],
        ),
    ]
