# Generated by Django 2.2.10 on 2020-06-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200612_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='service_token',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='service_token',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
