# Generated by Django 2.2.10 on 2020-07-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200629_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprinter',
            name='current_print',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='discord_webhook',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='print_notification_by_discord',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='HistoricalPrint',
        ),
        migrations.DeleteModel(
            name='HistoricalPrinter',
        ),
    ]
