# Generated by Django 2.2.10 on 2020-07-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_printshotfeedback_persisted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_webhook',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='print_notification_by_discord',
            field=models.BooleanField(default=True),
        ),
    ]
