# Generated by Django 2.2.10 on 2020-08-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_printshotfeedback_persisted_at'),
        ('app', '0038_auto_20200728_2028'),
    ]

    operations = [
    ]
