# Generated by Django 2.2.10 on 2021-01-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20201212_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printshotfeedback',
            name='print',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Print'),
        ),
    ]
