# Generated by Django 2.2.10 on 2020-12-26 01:02

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20201212_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('expired_at', models.DateTimeField(db_index=True, default=app.models.two_hours_later)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Printer')),
            ],
        ),
    ]
