# Generated by Django 2.2.10 on 2020-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20201226_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='estimated_finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='gone_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='status_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('DETECTED', 'DETECTED'), ('ENDED', 'ENDED'), ('GONE', 'GONE'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED')], max_length=20, null=True),
        ),
    ]
