# Generated by Django 2.2.10 on 2021-03-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210315_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintHeaterTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('target', models.FloatField()),
                ('offset', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Print')),
            ],
            options={
                'unique_together': {('print', 'name')},
            },
        ),
    ]
