# Generated by Django 2.2.10 on 2021-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210430_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_app_canary',
            field=models.BooleanField(default=False),
        ),
    ]
