# Generated by Django 2.2.10 on 2021-06-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210506_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='watching',
            new_name='watching_enabled',
        ),
        migrations.AlterField(
            model_name='printer',
            name='watching_enabled',
            field=models.BooleanField(db_column='watching', default=True),
        ),
    ]
