# Generated by Django 2.2.24 on 2021-09-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210925_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_short',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
