# Generated by Django 2.2.24 on 2021-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20211022_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='printertunnel',
            name='internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='printertunnel',
            name='basicauth_password',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='printertunnel',
            name='basicauth_username',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='printertunnel',
            name='subdomain_code',
            field=models.TextField(unique=True),
        ),
    ]
