# Generated by Django 2.2.24 on 2022-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20220109_1725'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='printer',
                    old_name='watching',
                    new_name='watching_enabled',
                ),
                migrations.AlterField(
                    model_name='printer',
                    name='watching_enabled',
                    field=models.BooleanField(db_column='watching', default=True),
                ),
            ]
        )
    ]
