# Generated by Django 2.2.24 on 2022-01-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20220112_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tunnel_cap_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
