# Generated by Django 2.2.24 on 2022-02-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20220112_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_filament_change_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED'), ('FILAMENT_CHANGE_REQ', 'FILAMENT_CHANGE_REQ')], max_length=20, null=True),
        ),
    ]
