# Generated by Django 2.2.27 on 2022-04-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_notificationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='notify_on_account_events',
        ),
    ]
