{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obico.fullname" . }}-media
  labels:
    {{- include "obico.labels" . | nindent 4 }}
  {{- if .Values.persistence.media.retain }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClassName }}
  storageClassName: {{ .Values.persistence.media.storageClassName }}
  {{- end }}
{{- end }}
