{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obico.fullname" . }}-data
  labels:
    {{- include "obico.labels" . | nindent 4 }}
  {{- if .Values.persistence.data.retain }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  {{- end }}
{{- end }}
