{{- if not .Values.obico.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obico.fullname" . }}
  labels:
    {{- include "obico.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ include "obico.secretKey" . | quote }}
  {{- range $key, $value := .Values.obico.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
