"""add user_id to printers

Revision ID: e183977963be
Revises: 6b253cec0d30
Create Date: 2019-01-04 22:37:06.119912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e183977963be'
down_revision = '6b253cec0d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'printer', 'user', ['user_id'], ['id'])
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_constraint(None, 'printer', type_='foreignkey')
    op.drop_column('printer', 'user_id')
    # ### end Alembic commands ###
