# Generated by Django 2.1.7 on 2019-08-20 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprint',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprint',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='print',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalprint',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Printer'),
        ),
        migrations.AlterField(
            model_name='print',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
