# Generated by Django 2.1.11 on 2019-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191213_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='print',
            unique_together={('printer', 'ext_id')},
        ),
    ]
