# Generated by Django 2.2.24 on 2022-03-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20220215_1206'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                select * from app_printevent where event_type in ('FILAMENT_CHANGE_REQ', 'USER_INTERACTION_REQ')
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='printevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED'), ('FILAMENT_CHANGE', 'FILAMENT_CHANGE')], max_length=20, null=True),
        ),
    ]
