/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guideSidebar: [
    'octoprint-plugin-setup',
    {
      type: 'category',
      label: 'Failure Detection',
      items: ['how-to-test-failure-detection', 'failure-detection-false-alarms', 'optimal-camera-setup','how-does-credits-work', 'help-the-detective-improve', 'detective-not-watching',],
    },
    {
      type: 'category',
      label: 'Use The App',
      items: ['detection-print-job-settings', 'printer-feed-sharing', 'octoprint-tunneling', 'octoprint-plugin-setup-manual-link', 'notification-settings'],
    },
    {
      type: 'category',
      label: 'Webcam Streaming',
      items: [
        'webcam-streaming-for-human-eyes',
        'more-about-webcam-streaming',
        'optimal-camera-setup',
        'webcam-streaming-resolution-framerate',
        {
          type: 'category',
          label: 'More... ',
          items: [
            'streaming-compatibility-mode',
            'adjust-webcam-settings-premium-streaming',
            'check-webcam-streaming-mode',
            'internet-speed-requirement-premium-streaming',
            'premium-streaming-raspberry-pi-connection-speed',
            'premium-streaming-computer-phone-connection-speed',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Account & Subscription',
      items: ['upgrade-to-pro', 'free-trial-pro-plan', 'check-type-of-your-account', 'how-does-detective-hour-work', 'unarchive-printer', 'open-source', ],
    },
    {
      type: 'category',
      label: 'Troubleshooting Guides',
      items: [
        'troubleshoot-server-connection-issues',
        {
          type: 'category',
          label: 'Webcam Streaming Troubleshooting',
          items: [
            'webcam-feed-is-not-showing',
            'webcam-feed-is-laggy',
            'premium-streaming-stuck-in-basic-mode',
            'octoprint-webcam-not-streaming',
          ],
        },
        'connectivity-error-report',
        'turn-on-debug-logging',
        'send-mobile-app-log-files',
      ],
    },
    'contact-us-for-support',
  ],
};
