/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guideSidebar: [
    'user_guides/octoprint-plugin-setup',
    {
      type: 'category',
      label: 'Failure Detection',
      items: ['user_guides/how-to-test-failure-detection', 'user_guides/failure-detection-false-alarms', 'user_guides/optimal-camera-setup', 'user_guides/how-does-credits-work', 'user_guides/help-the-detective-improve', 'user_guides/detective-not-watching',],
    },
    {
      type: 'category',
      label: 'Use The App',
      items: ['user_guides/detection-print-job-settings', 'user_guides/printer-feed-sharing', 'user_guides/octoprint-tunneling', 'user_guides/octoprint-plugin-setup-manual-link', 'user_guides/notification-settings'],
    },
    {
      type: 'category',
      label: 'Webcam Streaming',
      items: [
        'user_guides/webcam-streaming-for-human-eyes',
        'user_guides/more-about-webcam-streaming',
        'user_guides/optimal-camera-setup',
        'user_guides/webcam-streaming-resolution-framerate',
        {
          type: 'category',
          label: 'More... ',
          items: [
            'user_guides/streaming-compatibility-mode',
            'user_guides/adjust-webcam-settings-premium-streaming',
            'user_guides/check-webcam-streaming-mode',
            'user_guides/internet-speed-requirement-premium-streaming',
            'user_guides/premium-streaming-raspberry-pi-connection-speed',
            'user_guides/premium-streaming-computer-phone-connection-speed',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Account & Subscription',
      items: ['user_guides/upgrade-to-pro', 'user_guides/free-trial-pro-plan', 'user_guides/check-type-of-your-account', 'user_guides/how-does-detective-hour-work', 'user_guides/unarchive-printer', 'user_guides/open-source', ],
    },
    {
      type: 'category',
      label: 'Troubleshooting Guides',
      items: [
        'user_guides/troubleshoot-server-connection-issues',
        {
          type: 'category',
          label: 'Webcam Streaming Troubleshooting',
          items: [
            'user_guides/webcam-feed-is-not-showing',
            'user_guides/webcam-feed-is-laggy',
            'user_guides/premium-streaming-stuck-in-basic-mode',
            'user_guides/octoprint-webcam-not-streaming',
          ],
        },
        'user_guides/connectivity-error-report',
        'user_guides/turn-on-debug-logging',
        'user_guides/send-mobile-app-log-files',
      ],
    },
    'user_guides/contact-us-for-support',
  ],
  developerSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developing Plugins',
      link: {type: 'doc', id: 'developer_guides/plugins/index'},
      items: [
        'developer_guides/plugins/notification-plugin',
      ],
    },
  ],
};
