# Generated by Django 2.1.5 on 2019-01-24 22:47

from django.db import migrations

def create_seed_data(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    User = apps.get_model('app', 'User')
    User.objects.create(email='root@example.com', password='pbkdf2_sha256$120000$66yoUJRxbr6b$+Z9Ky4ZG/egqZQQkZPIPsvOKlTHIlZwl+xLY0E8qSfo=', is_superuser=True, is_staff=True, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_seed_data),
    ]
