# Generated by Django 2.1.5 on 2019-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190202_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just email me.'), ('PAUSE', 'Pause the print and email me.'), ('CANCEL', 'Cancel the print and email me (not available in beta testing).')], default='PAUSE', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalprinter',
            name='bed_off_on_pause',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalprinter',
            name='tools_off_on_pause',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just email me.'), ('PAUSE', 'Pause the print and email me.'), ('CANCEL', 'Cancel the print and email me (not available in beta testing).')], default='PAUSE', max_length=10),
        ),
        migrations.AddField(
            model_name='printer',
            name='bed_off_on_pause',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='tools_off_on_pause',
            field=models.BooleanField(default=True),
        ),
    ]
