# Generated by Django 2.1.7 on 2019-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_create_printer_preidction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprinter',
            name='detective_sensitivity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='printer',
            name='detective_sensitivity',
            field=models.FloatField(default=1.0),
        ),
    ]
