# Generated by Django 2.1.7 on 2019-05-19 12:15

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_print_fields_from_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='alert_muted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='HistoricalPrint',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('ext_id', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(max_length=1000)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('alerted_at', models.DateTimeField(null=True)),
                ('alert_acknowledged_at', models.DateTimeField(null=True)),
                ('alert_muted_at', models.DateTimeField(null=True)),
                ('video_url', models.CharField(max_length=2000, null=True)),
                ('tagged_video_url', models.CharField(max_length=2000, null=True)),
                ('poster_url', models.CharField(max_length=2000, null=True)),
                ('prediction_json_url', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Printer')),
            ],
            options={
                'verbose_name': 'historical print',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
