# Generated by Django 2.1.7 on 2019-08-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_pushbullet_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprint',
            name='alert_overwrite',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('NOT_FAILED', 'NOT_FAILED'), ('PARTIALY_FAILED', 'PARTIALY_FAILED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalprint',
            name='paused_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='alert_overwrite',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('NOT_FAILED', 'NOT_FAILED'), ('PARTIALY_FAILED', 'PARTIALY_FAILED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='paused_at',
            field=models.DateTimeField(null=True),
        ),
    ]
