# Generated by Django 2.1.7 on 2019-11-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191107_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalprinter',
            name='updated_at',
        ),
    ]
