# Generated by Django 2.2.10 on 2020-06-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200522_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprint',
            name='access_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='access_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printshotfeedback',
            name='answer',
            field=models.CharField(blank=True, choices=[('LOOKS_BAD', 'It contains spaghetti'), ('LOOKS_OK', 'It does NOT contain spaghetti'), ('UNDECIDED', "I'll decide later")], db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='printshotfeedback',
            name='answered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
