# Generated by Django 2.2.10 on 2020-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200629_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='printshotfeedback',
            name='persisted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
