# Generated by Django 2.2.10 on 2020-11-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20201123_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevice',
            name='device_token',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='mobiledevice',
            unique_together={('user', 'device_token')},
        ),
    ]
