# Generated by Django 2.2.10 on 2021-04-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210325_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='service_token',
        ),
    ]
