# Generated by Django 2.2.24 on 2021-09-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210506_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='min_timelapse_secs_on_cancel',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='printer',
            name='min_timelapse_secs_on_finish',
            field=models.IntegerField(default=600),
        ),
    ]
