# Generated by Django 2.2.24 on 2021-10-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210925_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicTimelapse',
        ),
    ]
