# Generated by Django 2.2.27 on 2022-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20220305_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatertracker',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='app_version',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='platform',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='preferred_timezone',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='onetimeverificationcode',
            name='code',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='print',
            name='alert_overwrite',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('NOT_FAILED', 'NOT_FAILED'), ('PARTIALY_FAILED', 'PARTIALY_FAILED')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='action_on_failure',
            field=models.CharField(choices=[('NONE', 'Just notify me'), ('PAUSE', 'Pause the printer and notify me')], default='PAUSE', max_length=256),
        ),
        migrations.AlterField(
            model_name='printer',
            name='auth_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='printercommand',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SENT', 'sent'), ('ABORTED', 'aborted')], default='PENDING', max_length=256),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED'), ('FILAMENT_CHANGE', 'FILAMENT_CHANGE')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='printheatertarget',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='printshotfeedback',
            name='answer',
            field=models.CharField(blank=True, choices=[('LOOKS_BAD', 'It contains spaghetti'), ('LOOKS_OK', 'It does NOT contain spaghetti'), ('UNDECIDED', "I'll decide later")], db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sharedresource',
            name='share_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pushbullet_access_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pushover_user_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slack_access_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
