# Generated by Django 2.2.27 on 2022-06-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_notificationsetting'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                update app_print set alert_overwrite = 'FAILED' where alert_overwrite = 'PARTIALY_FAILED'
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='alert_by_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alert_by_sms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discord_webhook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_canceled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_done',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_on_filament_change_req',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_country_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='print_notification_by_discord',
        ),
        migrations.RemoveField(
            model_name='user',
            name='print_notification_by_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='print_notification_by_pushbullet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='print_notification_by_pushover',
        ),
        migrations.RemoveField(
            model_name='user',
            name='print_notification_by_telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pushbullet_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pushover_user_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slack_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='print',
            name='alert_overwrite',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('NOT_FAILED', 'NOT_FAILED')], max_length=256, null=True),
        ),
    ]
