# Generated by Django 2.2.27 on 2022-08-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20220602_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='agent_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='agent_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
