# Generated by Django 2.2.27 on 2022-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20220602_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='x_inverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='y_inverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='z_inverted',
            field=models.BooleanField(default=False),
        ),
    ]
