# Generated by Django 2.2.27 on 2022-09-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20220822_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printevent',
            name='alert_muted',
        ),
        migrations.AddField(
            model_name='printevent',
            name='event_class',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('SUCCESS', 'SUCCESS'), ('INFO', 'INFO')], db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='event_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='event_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='help_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Printer'),
        ),
        migrations.AddField(
            model_name='printevent',
            name='visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Print'),
        ),
    ]
