# Generated by Django 2.2.27 on 2022-09-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20220822_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printevent',
            name='alert_muted',
        ),
        migrations.AddField(
            model_name='printevent',
            name='event_class',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('SUCCESS', 'SUCCESS'), ('INFO', 'INFO')], db_index=True, default='INFO', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printevent',
            name='event_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='event_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='help_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printevent',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Printer'),
        ),
        migrations.AddField(
            model_name='printevent',
            name='visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='unseen_printer_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED'), ('FILAMENT_CHANGE', 'FILAMENT_CHANGE'), ('PRINTER_ERROR', 'PRINTER_ERROR')], default='UNKNOWN', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printevent',
            name='print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Print'),
        ),
    ]
