# Generated by Django 2.2.27 on 2022-09-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20220920_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printevent',
            name='alert_muted',
        ),
    ]
