# Generated by Django 2.2.27 on 2022-09-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20220922_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintEvent',
            new_name='PrinterEvent',
        ),
    ]
