# Generated by Django 2.2.27 on 2022-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20220919_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printevent',
            name='event_type',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('PAUSED', 'PAUSED'), ('RESUMED', 'RESUMED'), ('FAILURE_ALERTED', 'FAILURE_ALERTED'), ('ALERT_MUTED', 'ALERT_MUTED'), ('ALERT_UNMUTED', 'ALERT_UNMUTED'), ('FILAMENT_CHANGE', 'FILAMENT_CHANGE'), ('PRINTER_ERROR', 'PRINTER_ERROR')], db_index=True, max_length=256),
        ),
    ]
