# Generated by Django 2.2.27 on 2022-11-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20220922_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='g_code_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.GCodeFile'),
        ),
    ]
