# Generated by Django 2.2.27 on 2022-11-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_print_g_code_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcodefile',
            name='agent_signature',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='resident_printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Printer'),
        ),
        migrations.AlterField(
            model_name='gcodefile',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
