# Generated by Django 2.2.27 on 2022-11-23 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20221122_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCodeFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('safe_name', models.CharField(db_index=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.GCodeFolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.GCodeFolder'),
        ),
        migrations.AddConstraint(
            model_name='gcodefolder',
            constraint=models.UniqueConstraint(fields=('user', 'parent_folder', 'safe_name'), name='unique_with_parent_folder'),
        ),
        migrations.AddConstraint(
            model_name='gcodefolder',
            constraint=models.UniqueConstraint(condition=models.Q(parent_folder=None), fields=('user', 'safe_name'), name='unique_without_parent_folder'),
        ),
    ]
