# Generated by Django 2.2.27 on 2023-01-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20221123_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcodefile',
            name='estimated_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='filament_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='metadata_json',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='thumbnail1_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='thumbnail2_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gcodefile',
            name='thumbnail3_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='filament_used',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='print_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='started_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
