# Generated by Django 2.2.27 on 2023-05-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20230128_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='single_printer_redirect_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
