
# Generated by Django 4.0.10 on 2024-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20231009_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_on_print_pause',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_on_print_resume',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_on_print_start',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunSQL(
            "UPDATE app_notificationsetting SET notify_on_print_pause = TRUE WHERE notify_on_other_print_events = TRUE;",
            "UPDATE app_notificationsetting SET notify_on_print_pause = FALSE WHERE notify_on_other_print_events = FALSE;"
        ),
    ]