# Generated by Django 4.0.10 on 2024-01-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_notificationsetting_notify_on_print_pause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='notify_on_other_print_events',
        ),
    ]
