# Generated by Django 4.0.10 on 2024-03-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_remove_notificationsetting_notify_on_other_print_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('streaming_params_json', models.TextField(blank=True, default='{}')),
                ('snapshot_enabled', models.BooleanField(default=True)),
                ('watching_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.printer')),
            ],
            options={
                'unique_together': {('printer', 'name')},
            },
        ),
    ]
