# Generated by Django 4.0.10 on 2024-05-09 01:01

from django.db import migrations, models
import django.db.models.deletion

def update_username(apps, schema_editor):
    User = apps.get_model('app', 'User')
    for user in User.objects.all():
        user.username = f'{user.email}_1'
        user.save()

def create_syndicate(apps, schema_editor):
    Syndicate = apps.get_model('app', 'Syndicate')
    Site = apps.get_model('sites', 'Site')
    syndicate = Syndicate.objects.create(id=1, name='base')
    syndicate.sites.add(*Site.objects.all())

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('app', '0076_remove_notificationsetting_notify_on_other_print_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Syndicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sites', models.ManyToManyField(related_name='syndicates', to='sites.site')),
            ],
        ),
        migrations.RunPython(create_syndicate, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='syndicate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.syndicate'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'syndicate')},
        ),
        migrations.RunPython(update_username, migrations.RunPython.noop),
    ]
