# Generated by Django 4.0.10 on 2024-05-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_user_username'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS unique_verified_email;
            """
        ),
    ]