# Generated by Django 4.0.10 on 2024-05-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_set_django_site_localhost_3334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLayerInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('video_url', models.CharField(max_length=2000, null=True)),
                ('tagged_video_url', models.CharField(max_length=2000, null=True)),
                ('data_json_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.print')),
            ],
        ),
        migrations.CreateModel(
            name='FirstLayerInspectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('labels', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_layer_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firstlayerinspection')),
            ],
        ),
    ]
