# Generated by Django 4.0.10 on 2024-05-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_set_django_site_localhost_3334'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicate',
            name='address_in_emails',
            field=models.CharField(default='1790 Willow Lake Ln, San jose, CA 95131', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syndicate',
            name='privacy_link',
            field=models.CharField(default='https://www.obico.io/privacy.html', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syndicate',
            name='terms_of_use_link',
            field=models.CharField(default='https://www.obico.io/terms.html', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syndicate',
            name='website',
            field=models.CharField(default='https://www.obico.io', max_length=255),
            preserve_default=False,
        ),
    ]
