# Generated by Django 4.0.10 on 2024-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_firstlayerinspection_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='detection_bending_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
