# Generated by Django 4.0.10 on 2025-05-20 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_printer_detection_bending_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='JusPrinChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('machine_name', models.TextField(blank=True, null=True)),
                ('filament_name', models.TextField(blank=True, null=True)),
                ('print_process_name', models.TextField(blank=True, null=True)),
                ('slicing_settings_json', models.TextField(blank=True, null=True)),
                ('user_feedback', models.CharField(blank=True, max_length=16, null=True)),
                ('user_feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
