# Generated by Django 4.0.10 on 2025-07-03 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_ai_credits_for_existing_users(apps, schema_editor):
    """Create JusPrinAICredit records for all existing users with unlimited quota (-1)."""
    User = apps.get_model('app', 'User')
    JusPrinAICredit = apps.get_model('app', 'JusPrinAICredit')

    # Get all existing users
    existing_users = User.objects.all()

    # Create AI credit records for all existing users with unlimited quota
    ai_credits_to_create = []
    for user in existing_users:
        ai_credits_to_create.append(
            JusPrinAICredit(
                user=user,
                ai_credit_free_monthly_quota=-1,  # Unlimited quota for existing users
                ai_credit_used_current_month=0
            )
        )

    # Bulk create all records
    if ai_credits_to_create:
        JusPrinAICredit.objects.bulk_create(ai_credits_to_create)
        print(f"Created AI credit records for {len(ai_credits_to_create)} existing users with unlimited quota")


def reverse_create_ai_credits_for_existing_users(apps, schema_editor):
    """Remove all JusPrinAICredit records (reverse operation)."""
    JusPrinAICredit = apps.get_model('app', 'JusPrinAICredit')
    JusPrinAICredit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_jusprinchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='JusPrinAICredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_credit_free_monthly_quota', models.IntegerField(default=-1)),
                ('ai_credit_used_current_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            create_ai_credits_for_existing_users,
            reverse_create_ai_credits_for_existing_users
        ),
    ]
