# Generated by Django 4.0.10 on 2025-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_jusprinaicredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerprediction',
            name='normalized_p',
            field=models.FloatField(default=0.0),
        ),
    ]
