# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_jusprinaicredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fd_2nd_gen_enabled',
            field=models.BooleanField(blank=False, default=False, null=False),
        ),
    ]
